## -*- encoding: utf-8 -*-
## This file (main.sagetex.sage) was *autogenerated* from main.tex with sagetex.sty version 2022/08/21 v3.6.1.
import sagetex
_st_ = sagetex.SageTeXProcessor('main', version='2022/08/21 v3.6.1', version_check=True)
try:
 _st_.current_tex_line = 93
 _st_.commandline(0, r"""
  sage: f(x)=sin(x)/x
  sage: limit(f,x,0)
""", globals(), locals(), True)
except:
 _st_.goboom(96)
_st_.endofdoc()
