## -*- encoding: utf-8 -*-
## This file (main.sagetex.sage) was *autogenerated* from main.tex with sagetex.sty version 2022/08/21 v3.6.1.
import sagetex
_st_ = sagetex.SageTeXProcessor('main', version='2022/08/21 v3.6.1', version_check=True)
