r"""
This file was *autogenerated* from main.tex with sagetex.sty
version 2022/08/21 v3.6.1. It contains the contents of all the
sageexample environments from main.tex. You should be able to
doctest this file with "sage -t main_doctest.sage".

It is always safe to delete this file; it is not used in typesetting your
document.

Sage commandline, line 94::

  sage: f(x)=sin(x)/x
  sage: f.limit(x=0)

"""
